version: '3.8'

services:
  hugo:
    image: sebbycorp/xademy-hugo-server:am64
    volumes:
      - .:/hugo
    ports:
      - "1313:1313"
    command: ["hugo", "server", "--bind", "0.0.0.0", "--watch"]
